import '#/styles/globals.css';
import { HeaderNav } from '#/ui/header-nav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderNav />

        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
